version: '3.4'

services:
  file-api:
    image: file-api
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV}
      - GOOGLE_OAUTH_ISSUER=${GOOGLE_OAUTH_ISSUER}
      - GOOGLE_OAUTH_AUDIENCE=${GOOGLE_OAUTH_AUDIENCE}
      - GOOGLE_OAUTH_CLIENT_SECRET=${GOOGLE_OAUTH_CLIENT_SECRET}
      - SAINT_PORTAL_API_KEY=${SAINT_PORTAL_API_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_ENDPOINT=${S3_ENDPOINT}
    volumes:
      - ./logs:/logs
    ports:
      - 3001:80
    restart: always

networks:
  default:
    external: true
    name: local-network
